application:
  title: "Notification Microservice"
  version: 1.0.0

server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ead_notification
    user: root
    password: Encrypt@Root
  jpa:
    hibernate:
      ddl-auto: update
      jdbc:
        lob.non-contextual-creation: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
